google/conscrypt

README.md

Update documentation about 'android' module output.

---

common/src/jni/main/cpp/JniConstants.cpp
common/src/jni/main/cpp/org_conscrypt_NativeCrypto.cpp
common/src/jni/main/include/JniConstants.h
common/src/jni/main/include/Trace.h
common/src/jni/main/include/macros.h

Split out JniConstants

---

android/src/main/java/org/conscrypt/Platform.java
common/src/jni/main/cpp/CompatibilityCloseMonitor.cpp
common/src/jni/main/cpp/JniConstants.cpp
common/src/jni/main/cpp/org_conscrypt_NativeCrypto.cpp
common/src/jni/main/include/CompatibilityCloseMonitor.h
common/src/jni/main/include/JniConstants.h
common/src/jni/main/include/OpenSslError.h
common/src/jni/main/include/ScopedSslBio.h
common/src/jni/main/include/Trace.h
common/src/jni/main/include/macros.h
common/src/jni/unbundled/cpp/JNIHelp.cpp
common/src/jni/unbundled/include/JNIHelp.h
common/src/jni/unbundled/include/ScopedLocalRef.h
common/src/jni/unbundled/include/ScopedPrimitiveArray.h

This isn't being checked by travis, so it tends to slip in.
Change-Id: I0e588e2dfd7fe9e3f6dab2eb68c54ffacef21b19

Fix new clang-format violations

---

Android.bp
Android.mk

Change-Id: I875c5c17ddb99d2b2fad4486ef04113d71c8711d

Fix Android build files

---

.travis.yml

This runs a MacOS build on Travis to make sure everything is working there as well.

Add MacOS X build to Travis

---

.travis.yml
appveyor.yml
build.gradle
common/src/jni/main/cpp/NativeCrypto.cpp
common/src/jni/main/cpp/jni_load.cpp
common/src/jni/main/include/JniUtil.h
common/src/jni/main/include/NativeCrypto.h
common/src/jni/main/include/macros.h
openjdk/build.gradle
openjdk/src/main/java/org/conscrypt/NativeCryptoJni.java

I'm not really sure of an easy way to test this ATM, since the library would have to be statically linked with the JVM. I think for now, we should just get this in and cross the testing bridge when we get there.
Fixes #33

Adding support for Java 8 static linking.

---

common/src/jni/main/cpp/NativeCrypto.cpp

This is a recently-added BoringSSL API which avoids the mess around
client and server distinctions.

Use SSL_get_peer_full_cert_chain.

---

common/src/jni/main/cpp/NativeCrypto.cpp
common/src/jni/main/include/Errors.h
common/src/jni/main/include/macros.h
common/src/jni/unbundled/include/ScopedLocalRef.h
openjdk/build.gradle

Add some warning suppressions and some MS VC++ compatibility with the code annotations.

Less warnings on Windows

---

build.gradle
common/src/main/java/org/conscrypt/OpenSSLEngineSocketImpl.java
common/src/main/java/org/conscrypt/OpenSSLServerSocketFactoryImpl.java
common/src/main/java/org/conscrypt/OpenSSLServerSocketImpl.java
common/src/main/java/org/conscrypt/OpenSSLSocketFactoryImpl.java
common/src/main/java/org/conscrypt/SSLUtils.java
openjdk-benchmarks/src/jmh/java/org/conscrypt/benchmarks/ClientSocketBenchmark.java
openjdk-testing/src/main/java/org/conscrypt/testing/EchoServer.java
openjdk-testing/src/main/java/org/conscrypt/testing/NettyEchoServer.java
openjdk-testing/src/main/java/org/conscrypt/testing/TestClient.java
openjdk-testing/src/main/java/org/conscrypt/testing/TestUtil.java
openjdk/src/test/java/org/conscrypt/OpenSSLServerSocketImplTest.java

Also adding simple unit test for server socket. This required moving some more test classes to the testing module.

Adding engine support to server socket.

---

openjdk/src/main/java/org/conscrypt/NativeLibraryLoader.java

This replaces a call from the native library loader to File.createTempFile with an internal implementation that does not depend the default SecureRandom security provider to have been initialized. Fixes #83.

Remove SecureRandom dependency in native loader.

---

openjdk-testing/src/main/java/org/conscrypt/testing/TestUtil.java

Switch from loading the old files to using TestKeyStore.
There appears to be a bug somewhere where the whole certificate chain
isn't being sent. Use the test root CA as the server for now.

Use TestKeyStore for Netty context init

---

common/src/main/java/org/conscrypt/OpenSSLEngineImpl.java
constants/build.gradle
openjdk-benchmarks/src/jmh/java/org/conscrypt/benchmarks/ClientSocketThroughputBenchmark.java
openjdk-benchmarks/src/jmh/java/org/conscrypt/benchmarks/ServerSocketThroughputBenchmark.java
openjdk-benchmarks/src/jmh/java/org/conscrypt/benchmarks/SslEngineBenchmark.java
openjdk-testing/src/main/java/org/conscrypt/testing/TestClient.java
openjdk-testing/src/main/java/org/conscrypt/testing/TestServer.java

Several changes to try to investigate why #93 helps in some benchmarks. Still can't replicate the problem with these benchmarks unfortunately.

Benchmark tweaks

---

openjdk/build.gradle

Strip binary on linux

---

RELEASING.md
build.gradle
openjdk-uber/build.gradle
openjdk/build.gradle

Adding boringssl version to manifest

---

common/src/jni/main/cpp/NativeCrypto.cpp
common/src/main/java/org/conscrypt/NativeCrypto.java

Remove insecure DHE groups

---

android-stub/build.gradle

Don't include android-stub in distribution

---

android/build.gradle
constants/build.gradle
openjdk/build.gradle
testing/build.gradle

Bundle conscrypt-constants in deployed artifacts.

---

android/build.gradle
build.gradle

Support deployment of android archives to Maven

---

android/build.gradle
common/src/main/java/org/conscrypt/AddressUtils.java
common/src/main/java/org/conscrypt/ArrayUtils.java
common/src/main/java/org/conscrypt/DuckTypedPSKKeyManager.java
common/src/main/java/org/conscrypt/EmptyArray.java
common/src/main/java/org/conscrypt/Internal.java
common/src/main/java/org/conscrypt/KeyManagerFactoryImpl.java
common/src/main/java/org/conscrypt/NativeCrypto.java
common/src/main/java/org/conscrypt/OpenSSLCipher.java
common/src/main/java/org/conscrypt/OpenSSLCipherRSA.java
common/src/main/java/org/conscrypt/OpenSSLContextImpl.java
common/src/main/java/org/conscrypt/OpenSSLEngineSocketImpl.java
common/src/main/java/org/conscrypt/OpenSSLSocketImpl.java
common/src/main/java/org/conscrypt/SSLNullSession.java
common/src/main/java/org/conscrypt/SSLParametersImpl.java
testing/src/main/java/libcore/java/security/TestKeyStore.java

Also locking down access to a couple utility classes.

Fixing various javadoc issues.

---

common/src/main/java/org/conscrypt/OpenSSLEngineImpl.java
common/src/main/java/org/conscrypt/OpenSSLEngineSocketImpl.java

Add handshake listener to engine.

---

android/src/main/java/org/conscrypt/KitKatPlatformOpenSSLSocketImplAdapter.java
android/src/main/java/org/conscrypt/Platform.java
android/src/main/java/org/conscrypt/PreKitKatPlatformOpenSSLSocketImplAdapter.java
api-doclet/src/main/java/org/conscrypt/doclet/FilterDoclet.java
common/src/main/java/org/conscrypt/FileClientSessionCache.java
common/src/main/java/org/conscrypt/OpenSSLCipher.java
common/src/main/java/org/conscrypt/OpenSSLExtendedSessionImpl.java
common/src/main/java/org/conscrypt/OpenSSLSignature.java
common/src/main/java/org/conscrypt/OpenSSLSocketImplWrapper.java

This fixes the rest of the warnings that Error-Prone is outputting during compilation.

Error-Prone fixes

---

common/src/main/java/org/conscrypt/Conscrypt.java

Expose common TLS constants.

---

common/src/jni/main/cpp/NativeCrypto.cpp

This unblocks BoringSSL from clearing out a lot of old hooks in
RSA_METHOD that are no longer used. Android keymaster follows a similar
pattern.

Use a more future-proof pattern to initialize RSA_METHOD.

---

benchmark-graphs/build.gradle
benchmark-graphs/src/main/java/org/conscrypt/graphgen/Main.java
benchmark-graphs/src/main/resources/html/footer.html
benchmark-graphs/src/main/resources/html/header.html
benchmark-graphs/src/main/resources/json/templates/SslEngineBenchmark.json
settings.gradle

This is a small utility that converts from JMH JSON output to a plotly
HTML file. This allows one to visualize the benchmark data easily.

Add benchmark graphing utility

---

common/src/main/java/org/conscrypt/SSLParametersImpl.java

Default to true for SNIEnabled on restricted platforms

---

common/src/main/java/org/conscrypt/OpenSSLExtendedSessionImpl.java
openjdk/src/main/java/org/conscrypt/Platform.java
openjdk/src/test/java/org/conscrypt/OpenSSLExtendedSessionImplTest.java
openjdk/src/test/java/org/conscrypt/PlatformTest.java

I wasn't able to figure out a way to make the Java 8 parts of OpenSSLExtendedSessionImpl.java work, so I removed it.

Make openjdk target support Java 7

---

common/src/main/java/org/conscrypt/OpenSSLEngineImpl.java
common/src/main/java/org/conscrypt/OpenSSLEngineSocketImpl.java
common/src/main/java/org/conscrypt/OpenSSLSocketFactoryImpl.java
common/src/main/java/org/conscrypt/OpenSSLSocketImplWrapper.java
openjdk/src/test/java/org/conscrypt/OpenSSLSocketImplTest.java

Also properly throwing SSLHandshakeException in some cases.
Fixes #191

Adding all factory methods for engine socket.

---

android/src/main/java/org/conscrypt/Platform.java
common/src/jni/main/cpp/NativeCrypto.cpp
common/src/main/java/org/conscrypt/Conscrypt.java
common/src/main/java/org/conscrypt/ConscryptEngine.java
common/src/main/java/org/conscrypt/NativeCrypto.java
common/src/main/java/org/conscrypt/OpenSSLContextImpl.java
common/src/main/java/org/conscrypt/OpenSSLEngineSocketImpl.java
common/src/main/java/org/conscrypt/OpenSSLSocketImpl.java
common/src/main/java/org/conscrypt/PeerInfoProvider.java
common/src/main/java/org/conscrypt/Preconditions.java
common/src/main/java/org/conscrypt/SSLUtils.java
openjdk-integ-tests/src/test/java/libcore/javax/net/ssl/SSLSocketTest.java
openjdk/src/main/java/org/conscrypt/Platform.java
openjdk/src/test/java/org/conscrypt/ConscryptEngineTest.java
openjdk/src/test/java/org/conscrypt/PlatformTest.java
platform/src/main/java/org/conscrypt/Platform.java

This is part of an overall fix for the engine socket. A later PR will
contain the rest of the changes, which will allow the SSLSocketTest
to pass for the engine-based socket.

Various fixes to the Conscrypt engine.

---

openjdk-integ-tests/src/test/java/libcore/javax/net/ssl/SSLSocketTest.java
openjdk/src/test/java/org/conscrypt/NativeCryptoTest.java
testing/src/main/java/libcore/java/security/TestKeyStore.java
testing/src/main/java/libcore/javax/net/ssl/TestSSLEnginePair.java

These problems were found when porting the changes to the tests back to Android's libcore project.

Various test fixes

---

.travis.yml
appveyor.yml

This fixes AppVeyor and Travis-CI builds.

Update to the new cmake

---

common/src/jni/main/cpp/NativeCrypto.cpp

I believe these are no longer necessary.

Clean up temporary BoringSSL #ifdefs.

---

common/src/jni/main/cpp/NativeCrypto.cpp
common/src/main/java/org/conscrypt/NativeCrypto.java
common/src/main/java/org/conscrypt/OpenSSLECPrivateKey.java
common/src/main/java/org/conscrypt/OpenSSLECPublicKey.java
common/src/main/java/org/conscrypt/OpenSSLKey.java
common/src/main/java/org/conscrypt/OpenSSLRSAPrivateKey.java
common/src/main/java/org/conscrypt/OpenSSLRSAPublicKey.java
platform/src/main/java/org/conscrypt/InternalUtil.java

Some parsing and serializing fixes.

---

common/src/jni/main/cpp/NativeCrypto.cpp
common/src/main/java/org/conscrypt/GCMParameters.java
common/src/main/java/org/conscrypt/NativeCrypto.java
common/src/main/java/org/conscrypt/OpenSSLProvider.java

In order to handle the ASN.1 encoding, exposes a subset of the ASN.1
encoding API from BoringSSL in NativeCrypto.

Implement AlgorithmParameters.GCM in Conscrypt.

---

openjdk/src/test/java/org/conscrypt/ConscryptSocketTest.java

This was created in an attempt to reproduce #104.
I suspect that FD socket will not work, since it writes directly to the socket's underlying file descriptor rather than going through the SSL socket. The engine-based socket, however, appears  to work fine.

Adding test for wrapping SSL socket.

---

common/src/main/java/org/conscrypt/BufferAllocator.java
common/src/main/java/org/conscrypt/ConscryptEngine.java
common/src/main/java/org/conscrypt/OpenSSLContextImpl.java
common/src/main/java/org/conscrypt/SSLNullSession.java
common/src/main/java/org/conscrypt/SSLParametersImpl.java

Removes unused variables, fixes cases of non-final ALL_CAPS_VARS, removes
wildcard import, adds default to non-exhaustive switch statement.

Fix a bunch of warnings.

---

android/build.gradle

Fixes #266
Upgrading the android tools plugin seems to do the trick.
Before:
ls -laF android/build/outputs/aar/conscrypt-android-*
-rw-r----- 1 nathanmittler eng 12538075 Aug  1 07:55 android/build/outputs/aar/conscrypt-android-debug.aar
-rw-r----- 1 nathanmittler eng 12455486 Aug  1 07:56 android/build/outputs/aar/conscrypt-android-release.aar
-rw-r----- 1 nathanmittler eng      475 Aug  1 07:56 android/build/outputs/aar/conscrypt-android-release.aar.asc
jar -tvf android/build/outputs/aar/conscrypt-android-release.aar
361499 Tue Aug 01 07:55:12 PDT 2017 classes.jar
0 Tue Aug 01 07:56:00 PDT 2017 jni/
0 Tue Aug 01 07:56:00 PDT 2017 jni/x86_64/
11055096 Tue Aug 01 07:56:00 PDT 2017 jni/x86_64/libconscrypt_jni.so
0 Tue Aug 01 07:56:00 PDT 2017 jni/x86/
10286428 Tue Aug 01 07:56:00 PDT 2017 …

Strip android binaries.

---

common/src/jni/main/cpp/NativeCrypto.cpp
common/src/main/java/org/conscrypt/ActiveSession.java
common/src/main/java/org/conscrypt/ConscryptEngine.java
common/src/main/java/org/conscrypt/ConscryptFileDescriptorSocket.java
common/src/main/java/org/conscrypt/NativeCrypto.java
common/src/main/java/org/conscrypt/SslWrapper.java
openjdk-integ-tests/src/test/java/libcore/javax/net/ssl/SSLSessionTest.java
openjdk/src/test/java/org/conscrypt/NativeCryptoTest.java

Closes issue #258. You'll want to review each commit individually. Pay particular attention to 3df5adf1ecab6f7294294d094efe851663d9f9b7 to make sure I didn't get confused about how the Java bits work.

Switch to TLS_with_buffers_method.

---

common/src/main/java/org/conscrypt/OpenSSLCipher.java

getOutputSize should consider in update() as well as doFinal()

---

common/src/main/java/org/conscrypt/AbstractSessionContext.java

Properly handle setSessionTimeout(0)

---

common/src/main/java/org/conscrypt/ConscryptEngineSocket.java

The special channel socket processing was meant to increase performance,
but seems to actually decrease performance on Android. It also
adds additional complexity to the socket code.

Remove channel-specific logic from engine socket.

---

android/src/main/java/org/conscrypt/Platform.java
common/src/main/java/org/conscrypt/AbstractConscryptSocket.java
openjdk/src/main/java/org/conscrypt/Platform.java
platform/src/main/java/org/conscrypt/Platform.java

(Cherry-picked from AOSP change 6f26eeff)

Use InetAddress originalHostName (if present) for getHostnameOrIP

---

android/src/main/java/org/conscrypt/Platform.java
common/src/main/java/org/conscrypt/OpenSSLProvider.java
libcore-stub/src/main/java/libcore/java/security/StandardNames.java
openjdk-integ-tests/src/test/java/libcore/javax/net/ssl/SSLSessionContextTest.java
openjdk/src/main/java/org/conscrypt/Platform.java
platform/src/main/java/org/conscrypt/Platform.java

Customize default provider name based on platform

---

android/src/main/java/org/conscrypt/Platform.java
common/src/main/java/org/conscrypt/OpenSSLBIOSource.java
openjdk/src/main/java/org/conscrypt/Platform.java
platform/src/main/java/org/conscrypt/Platform.java
platform/src/main/java/org/conscrypt/ct/Serialization.java

Also fixing a couple of new compiler warnings.

Fix back-compat issue from recent import.

---

.travis.yml
openjdk/src/main/java/org/conscrypt/Platform.java

Add Java 6 testing to Travis for Linux

---

common/src/jni/main/cpp/conscrypt/native_crypto.cc

I couldn't find anywhere that we're relying on the functionality behind
SSL_clear (indeed, the documentation of its behavior isn't very detailed
so I don't really know how we could), and BoringSSL recommends not using
it.  We allocate a separate SSL object per SSLEngine/SSLSocket, so we
aren't attempting to reuse them.  So this should be safe.

Remove all remaining uses of SSL_clear.

---

benchmark-android/src/main/java/org/conscrypt/AndroidEngineFactory.java
benchmark-base/src/main/java/org/conscrypt/EngineHandshakeBenchmark.java
benchmark-base/src/main/java/org/conscrypt/EngineWrapBenchmark.java
benchmark-jmh/src/jmh/java/org/conscrypt/OpenJdkEngineFactory.java
common/src/jni/main/cpp/conscrypt/native_crypto.cc
common/src/main/java/org/conscrypt/ActiveSession.java
common/src/main/java/org/conscrypt/ConscryptEngine.java
common/src/main/java/org/conscrypt/ConscryptEngineSocket.java
openjdk-integ-tests/src/test/java/libcore/javax/net/ssl/SSLContextTest.java
openjdk/src/test/java/org/conscrypt/ConscryptEngineTest.java
openjdk/src/test/java/org/conscrypt/MockSessionBuilder.java
openjdk/src/test/java/org/conscrypt/RenegotiationTest.java
testing/src/main/java/org/conscrypt/TestUtils.java

Support renegotiation with sockets

---

benchmark-android/src/main/java/org/conscrypt/AndroidEngineFactory.java
benchmark-jmh/src/jmh/java/org/conscrypt/OpenJdkEngineFactory.java
common/src/jni/main/cpp/conscrypt/native_crypto.cc
common/src/jni/main/include/conscrypt/app_data.h
common/src/main/java/org/conscrypt/AbstractConscryptEngine.java
common/src/main/java/org/conscrypt/AbstractConscryptSocket.java
common/src/main/java/org/conscrypt/ApplicationProtocolSelector.java
common/src/main/java/org/conscrypt/ApplicationProtocolSelectorAdapter.java
common/src/main/java/org/conscrypt/Conscrypt.java
common/src/main/java/org/conscrypt/ConscryptEngine.java
common/src/main/java/org/conscrypt/ConscryptEngineSocket.java
common/src/main/java/org/conscrypt/ConscryptFileDescriptorSocket.java
common/src/main/java/org/conscrypt/ConscryptSocketBase.java
common/src/main/java/org/conscrypt/Java8EngineWrapper.java
common/src/main/java/org/conscrypt/Java8SocketWrapper.java
common/src/main/java/org/conscrypt/NativeCrypto.java
common/src/main/java/org/conscrypt/OpenSSLSocketImpl.java
common/src/main/java/org/conscrypt/SSLParametersImpl.java
common/src/main/java/org/conscrypt/SSLUtils.java
common/src/main/java/org/conscrypt/SslWrapper.java
openjdk-integ-tests/src/test/java/libcore/javax/net/ssl/SSLContextTest.java
openjdk/src/main/java/org/conscrypt/Java8PlatformUtil.java
openjdk/src/main/java/org/conscrypt/Java9PlatformUtil.java
openjdk/src/main/java/org/conscrypt/Platform.java
openjdk/src/test/java/org/conscrypt/ApplicationProtocolSelectorAdapterTest.java
openjdk/src/test/java/org/conscrypt/ConscryptEngineTest.java
openjdk/src/test/java/org/conscrypt/ConscryptSocketTest.java
openjdk/src/test/java/org/conscrypt/NativeCryptoTest.java
openjdk/src/test/java/org/conscrypt/PlatformTest.java
openjdk/src/test/java/org/conscrypt/SSLUtilsTest.java

Add missing Java 9 methods for ALPN

---

BUILDING.md
appveyor.yml

Update AppVeyor to use MSVC 2017 and Platform SDK 10

---

common/src/jni/main/cpp/conscrypt/native_crypto.cc

The OPENSSL_VERSION_NUMBER change seems to have stuck!

Remove now unnecessary ifdef.

---

Android.bp
Android.mk

See build/soong/README.md for more information.
Test: m -j checkbuild

Convert external/conscrypt to Android.bp

---

common/src/main/java/org/conscrypt/OpenSSLCipherChaCha20.java
common/src/main/java/org/conscrypt/SSLUtils.java

We've seen a decodeProtocols failure in the wild, which is super weird,
so I'd like to see more details of whether the caller is at fault or
we are somehow.

Update some exception messages.

---

RELEASING.md
build.gradle

Added code to sign the jars before uploading if signing properties are
present and updated instructions.

Set up jar signing for release builds.

---

README.md

Change README to not link to v1.1.0 jars.

---

common/src/jni/main/cpp/conscrypt/native_crypto.cc
common/src/main/java/org/conscrypt/NativeCrypto.java
common/src/main/java/org/conscrypt/OpenSSLX509CRL.java
common/src/main/java/org/conscrypt/OpenSSLX509Certificate.java
openjdk/src/test/java/org/conscrypt/NativeCryptoTest.java
platform/src/main/java/org/conscrypt/InternalUtil.java
platform/src/main/java/org/conscrypt/TrustedCertificateStore.java
platform/src/main/java/org/conscrypt/ct/CTVerifier.java

This updates OpenSSLX509Certificate and OpenSSLX509CRL in the same way
as NativeSsl was done previously.

More finalization safety.

---

common/src/jni/main/cpp/conscrypt/native_crypto.cc
openjdk/src/test/java/org/conscrypt/AbstractSessionContextTest.java

Propose exludes call be excludes

---

Dockerfile

I use emacs as an editor and it's annoying when it's not there.

Install emacs in Docker images.

---

common/src/main/java/org/conscrypt/CryptoUpcalls.java

Use Conscrypt.isConscrypt() in CryptoUpcalls.

---

CONTRIBUTING.md
README.md

Add Android dependency snippets to README.md and reformat a bit.
Move the source code layout info from README.md to CONTRIBUTING.md.

Update basic docs.

---

README.md
build.gradle

Also update README.md for release of 1.2.0

Start 1.3 development cycle

---

common/src/main/java/org/conscrypt/ChainStrengthAnalyzer.java
common/src/main/java/org/conscrypt/TrustManagerImpl.java

This allows users to more easily debug failing chain construction.
Fixes #559.

Add debug logging to ChainStrengthAnalyzer

---

common/src/main/java/org/conscrypt/OpenSSLBIOInputStream.java
openjdk-integ-tests/src/test/java/org/conscrypt/java/security/cert/CertificateFactoryTest.java

Some of the callers of BIO APIs in BoringSSL (particularly the DER
decoder) depend on the BIO read returning either a full buffer or an
EOF, but InputStream allows returning less than the requested amount
of data without hitting EOF.  This causes the DER decoder to fail in
some cases (specifically, we've seen it fail with overly large OCSP
responses where the socket hasn't buffered the entire response before
we try to decode it).
Fix this by repeatedly calling read() until our output buffer is full
or EOF is reached.
Also add a test for decoding DER-encoded certs, we previously only
tested PEM-encoded ones.

Make OpenSSLBIOInputStream read as fully as possible

---

common/src/main/java/org/conscrypt/KeyManagerImpl.java
openjdk-integ-tests/src/test/java/org/conscrypt/javax/net/ssl/KeyManagerFactoryTest.java

The Android Keystore implementation of KeyStore doesn't implement
getEntry() and throws UnsupportedOperationException if you try to call
it.  We can adapt to that by attempting to retrieve the private key
and certificate chain manually if the call to getEntry() fails.
Fixes #685

Accommodate KeyStores that don't support getEntry()

---

openjdk-integ-tests/src/test/java/org/conscrypt/java/security/SignatureTest.java
openjdk-integ-tests/src/test/java/org/conscrypt/javax/crypto/CipherTest.java
openjdk-integ-tests/src/test/java/org/conscrypt/javax/net/ssl/SSLEngineVersionCompatibilityTest.java
openjdk-integ-tests/src/test/java/org/conscrypt/javax/net/ssl/SSLSocketTest.java
test_logging.properties

Clean up some unused variable and method ErrorProne warnings.
Eliminate debug logging from NativeLibraryLoader in tests.

Minor cleanup

---

common/src/main/java/org/conscrypt/FileClientSessionCache.java
common/src/main/java/org/conscrypt/KeyManagerFactoryImpl.java

Just a few things that are not severe issues. One could possibly leak a FileInputStream until finalization.

Fixes for issues found by lgtm.com

---

build.gradle
openjdk-uber/build.gradle
openjdk/build.gradle

Related to: https://github.com/google/conscrypt/issues/387

Add OSGi headers to uber jar manifest

---

BUILDING.md
android-stub/build.gradle
android/build.gradle
api-doclet/build.gradle
benchmark-base/build.gradle
benchmark-graphs/build.gradle
benchmark-jmh/build.gradle
build.gradle
constants/build.gradle
gradle/publishing.gradle
libcore-stub/build.gradle
openjdk-uber/build.gradle
openjdk/build.gradle
release/README.md
settings.gradle
testing/build.gradle

This just fixes some hacks that break in newer versions of Gradle.

Make some changes for Javadoc publishing

---

android/src/main/java/org/conscrypt/KitKatPlatformOpenSSLSocketImplAdapter.java
android/src/main/java/org/conscrypt/Platform.java
android/src/main/java/org/conscrypt/PreKitKatPlatformOpenSSLSocketImplAdapter.java
benchmark-base/src/main/java/org/conscrypt/EngineHandshakeBenchmark.java
common/src/main/java/org/conscrypt/OpenSSLX509Certificate.java
common/src/main/java/org/conscrypt/OpenSSLX509CertificateFactory.java
common/src/main/java/org/conscrypt/SSLParametersImpl.java
common/src/main/java/org/conscrypt/TrustManagerImpl.java
common/src/main/java/org/conscrypt/ct/CTVerifier.java
common/src/main/java/org/conscrypt/ct/SerializationException.java
common/src/test/java/org/conscrypt/TrustManagerImplTest.java
common/src/test/java/org/conscrypt/java/security/SignatureTest.java
common/src/test/java/org/conscrypt/java/security/cert/CertificateFactoryTest.java
common/src/test/java/org/conscrypt/javax/net/ssl/SSLEngineVersionCompatibilityTest.java
openjdk/src/test/java/org/conscrypt/MockSessionBuilder.java
openjdk/src/test/java/org/conscrypt/NativeCryptoTest.java
openjdk/src/test/java/org/conscrypt/PlatformTest.java
openjdk/src/test/java/org/conscrypt/RenegotiationTest.java
platform/src/main/java/org/conscrypt/CertBlacklistImpl.java
platform/src/main/java/org/conscrypt/TrustedCertificateStore.java
platform/src/main/java/org/conscrypt/ct/CTPolicyImpl.java
platform/src/test/java/org/conscrypt/TrustedCertificateStoreTest.java
platform/src/test/java/org/conscrypt/ct/CTLogStoreImplTest.java
testing/src/main/java/org/conscrypt/TestUtils.java
testing/src/main/java/org/conscrypt/javax/net/ssl/TestHostnameVerifier.java
testing/src/main/java/org/conscrypt/testing/BrokenProvider.java
testing/src/main/java/org/conscrypt/tlswire/handshake/CipherSuite.java
testing/src/main/java/org/conscrypt/tlswire/handshake/CompressionMethod.java
testing/src/main/java/org/conscrypt/tlswire/util/TlsProtocolVersion.java
testing/src/main/java/tests/util/Pair.java

This pull request fixes or suppresses all the ErrorProne and lint warnings that come out of the default build.

Fix all the warnings in the code base

---

common/src/jni/main/cpp/conscrypt/compatibility_close_monitor.cc
common/src/jni/main/cpp/conscrypt/native_crypto.cc
common/src/jni/main/include/conscrypt/NetFd.h
common/src/jni/main/include/conscrypt/app_data.h
common/src/jni/main/include/conscrypt/compatibility_close_monitor.h
common/src/jni/main/include/conscrypt/jniutil.h
common/src/jni/unbundled/include/nativehelper/scoped_local_ref.h
common/src/jni/unbundled/include/nativehelper/scoped_primitive_array.h
common/src/jni/unbundled/include/nativehelper/scoped_utf_chars.h
common/src/test/java/org/conscrypt/java/security/MessageDigestTest.java
common/src/test/java/org/conscrypt/java/security/SignatureTest.java
common/src/test/java/org/conscrypt/javax/crypto/CipherTest.java
openjdk/build.gradle
testing/src/main/java/tests/util/ServiceTester.java

When the refactor to the new maven-publish Gradle API was done, the native artifact for each platform
was not published to the repo. This pull fixes that problem.
It also fixes some tests on the platforms so that all the tests should pass on other providers as well.
Additionally if cpplint is installed there are a lot of errors during the release process due to code not
being formatted correctly. This also fixes all the cpplint problems.

Fix publishing to Maven repo

---

common/src/main/java/org/conscrypt/AbstractConscryptSocket.java
common/src/test/java/org/conscrypt/javax/net/ssl/SSLSocketVersionCompatibilityTest.java

Handle removal of a handshake listener during event delivery.

---

common/src/main/java/org/conscrypt/ActiveSession.java
common/src/main/java/org/conscrypt/ConscryptFileDescriptorSocket.java
common/src/main/java/org/conscrypt/ConscryptSession.java
common/src/main/java/org/conscrypt/ExternalSession.java
common/src/main/java/org/conscrypt/Java7ExtendedSSLSession.java
common/src/main/java/org/conscrypt/SSLNullSession.java
common/src/main/java/org/conscrypt/SessionSnapshot.java
openjdk/src/test/java/org/conscrypt/ConscryptEngineTest.java
openjdk/src/test/java/org/conscrypt/ConscryptSocketTest.java

Store application protocol in SessionSnapshot.

---

common/src/main/java/org/conscrypt/ConscryptEngineSocket.java

Upstreaming http://r.android.com/1186398.

ConscryptEngineSocket: Add no-op setHandshakeTimeout().

---

.github/workflows/ci.yml

notes:
https://github.com/actions/checkout/blob/master/README.md

GitHub Actions checkout v2

---

common/src/main/java/org/conscrypt/Conscrypt.java

It's not clear to me if our toolchain would allow me to use
try-with-resources here and it will get desugared for API
levels below 19.  Maybe I should just try it and see.

Close resources InputStream after use.  Fixes #801.

---

common/src/jni/main/cpp/conscrypt/native_crypto.cc

Untested but seems reasonable by inspection.

Release event after select on Windows. Fixes #799.

---

common/src/main/java/org/conscrypt/AbstractConscryptSocket.java
common/src/main/java/org/conscrypt/ConscryptEngineSocket.java
common/src/main/java/org/conscrypt/NativeCrypto.java
common/src/main/java/org/conscrypt/OpenSSLAeadCipher.java
common/src/main/java/org/conscrypt/OpenSSLX509Certificate.java
common/src/main/java/org/conscrypt/ShortBufferWithoutStackTraceException.java
common/src/main/java/org/conscrypt/TrustManagerImpl.java
common/src/main/java/org/conscrypt/ct/CTVerifier.java
testing/src/main/java/org/conscrypt/javax/net/ssl/TestHostnameVerifier.java

Correcting warnings from Google's linter plus a few style nits in
NativeCrypto. No functional changes.

Lint and style tidy-ups.

---

common/src/jni/main/cpp/conscrypt/native_crypto.cc

This mirrors the issuer alternate names logic. While OpenSSL does cache
the SAN list on x->altname, they did not add an accessor for it.
Instead, it seems the public API in OpenSSL is now to extract it anew.
This removes the need for calling X509_check_ca to populate the weird
extensions cache.

Extract the SAN list with X509_get_ext_d2i.

---

common/src/jni/main/cpp/conscrypt/native_crypto.cc

https://boringssl-review.googlesource.com/c/boringssl/+/42584
const-corrects a number of functions to align with OpenSSL upstream. So
Conscrypt and BoringSSL don't need to be updated atomically, I've added
wrappers so Conscrypt builds against both old and new BoringSSL. Once
the change has trickled through downstreams, we can remove the const
wrappers.
Fixes issue #883.

Smooth over BoringSSL const changes.

---

IMPLEMENTATION_NOTES.md

(sorry, should have done this along with the README)

Update implementation notes for 2.5.0

---

.github/workflows/ci.yml

Correct fix this time from https://github.com/actions/virtual-environments/issues/1811

Update MacOS CI workflow.

---

.github/workflows/ci.yml

And also invalid openssl version....

Fix incorrect comment characters in CI workflow.

---

common/src/main/java/org/conscrypt/OpenSSLECKeyFactory.java
common/src/main/java/org/conscrypt/OpenSSLRSAKeyFactory.java
common/src/test/java/org/conscrypt/java/security/KeyFactoryTestEC.java
common/src/test/java/org/conscrypt/java/security/KeyFactoryTestRSA.java

Flip isAssignableFrom checks in OpenSSLECKeyFactory and OpenSSLRSAKeyFactory

---

.github/workflows/ci.yml

Possibly no longer needed based on a) failure and b) https://github.com/stloeffler/texworks-testing/commit/f9ec52098696d500adf006ea50e722d6151dc9cb

Attempt to build without workaround for Mac homebrew

---

common/src/main/java/org/conscrypt/CertificatePriorityComparator.java
common/src/main/java/org/conscrypt/KeyManagerImpl.java
common/src/main/java/org/conscrypt/OpenSSLX509Certificate.java
common/src/main/java/org/conscrypt/TrustManagerImpl.java
common/src/test/java/org/conscrypt/java/security/SignatureTest.java

Trying to reduce the output from ErrorProne so it can be paid some attention when new issues pop up.

Miscellaneous code cleanups

---

common/src/main/java/org/conscrypt/metrics/OptionalMethod.java
common/src/test/java/org/conscrypt/ConscryptSuite.java
common/src/test/java/org/conscrypt/metrics/CipherSuiteTest.java
common/src/test/java/org/conscrypt/metrics/OptionalMethodTest.java
common/src/test/java/org/conscrypt/metrics/ProtocolTest.java

Plus some comment refactoring and null checking in  OptionalMethod.

Unit tests for stats support classes.

---

openjdk/src/test/java/org/conscrypt/ConscryptSocketTest.java

Mostly addresses #970.
Covers both client side and server side being a SocketChannel
and adds a test to send random blocks of data to ensure no
hangs.

Extend ConscryptSocketTest to cover SocketChannels.

---

common/src/main/java/org/conscrypt/OpenSSLX509CertificateFactory.java
common/src/test/java/org/conscrypt/java/security/cert/CertificateFactoryTest.java

Distinguish PKCS#7 and X.509 more accurately.

---

.travis.yml

Package no longer available on Travis which is causing
the whole CI to fail.

Remove Travis CI testing on Java 7.

---

common/src/main/java/org/conscrypt/metrics/OptionalMethod.java
common/src/test/java/org/conscrypt/metrics/OptionalMethodTest.java

Can happen if one of the parameter classes is not found.

OptionalMethod should tolerate null parameter class args.

---

common/src/jni/main/cpp/conscrypt/native_crypto.cc

The BoringSSL change has since landed.

Remove unnecessary const_cast.

---

constants/build.gradle
openjdk/build.gradle

Fixes CI and local Gradle builds.

Update C++ Standard flags to C++17

---

common/src/jni/main/cpp/conscrypt/jniutil.cc
common/src/test/java/org/conscrypt/java/security/cert/X509CertificateTest.java

Should be NoSuchAlgorithmException:
https://developer.android.com/reference/java/security/cert/X509Certificate?hl=en#verify(java.security.PublicKey,%20java.security.Provider)

Throw correct exception for unsupported digest algorithm.

---

common/src/jni/main/cpp/conscrypt/native_crypto.cc

In doing so, this removes the puts callback. BIO_puts in BoringSSL is implemented with BIO_write. We ignore the puts callback. I've also removed the create callback and deferred BIO_set_init to when the stream is attached. This makes no real difference, but since the BIO isn't usable until the stream is attached, BIO_set_init probably should be called later.

Use accessors for BIO and BIO_METHOD

---

common/src/jni/main/cpp/conscrypt/native_crypto.cc

We now always fill in n, so there's no reason to override this implementation.

Removed cached_size and RsaMethodSize

---

platform/src/main/java/org/conscrypt/TrustedCertificateStore.java
platform/src/test/java/org/conscrypt/TrustedCertificateStoreTest.java

Should bring platform/ mostly back into sync.  See individual commits for details.

Upstream multiple AOSP changes.

---

android/src/main/java/org/conscrypt/Platform.java
common/src/main/java/org/conscrypt/ConscryptEngine.java
common/src/main/java/org/conscrypt/ConscryptFileDescriptorSocket.java
openjdk/src/main/java/org/conscrypt/Platform.java
platform/src/main/java/org/conscrypt/Platform.java

Remove Platform.logEvent().

---

.github/workflows/ci.yml

Due to updated compiler mimima.

Bump MacOS target version for CI.

---

common/src/main/java/org/conscrypt/TrustManagerImpl.java

Reverts google/conscrypt#1223
Depends on #1221 which needs reverting.

Revert "Fix: null check ctLogStore"

---

common/src/main/java/org/conscrypt/metrics/CipherSuite.java
common/src/main/java/org/conscrypt/metrics/Protocol.java

Upstreams https://r.android.com/3009193

Change TLS metric Protocol/CipherSuite enums to use ints.

---

platform/src/main/java/org/conscrypt/ct/LogStoreImpl.java

Bug: 319829948
Test: Push log list to /data/misc/keychain/ct/v1/current/log_list.json
and run ctdemo app
Change-Id: Ie5e55332ca704f95486d18d4696d088aa4445c15

Add /current/ to log list path

---

platform/src/test/java/org/conscrypt/CertBlocklistTest.java
platform/src/test/java/org/conscrypt/ct/LogStoreImplTest.java

Test: atest ConscryptPrivateTestCases
Change-Id: I4df53fcdd9921f8a11c65b486e8301436ceef8d7

Move CertBlocklistTest and LogStoreImplTest to JUnit4

---

common/src/jni/main/cpp/conscrypt/native_crypto.cc
common/src/main/java/org/conscrypt/NativeCrypto.java
common/src/main/java/org/conscrypt/NativeRef.java

Change-Id: I072d6765291e4642265a1ef07c992f55c0ea9fa0
Bug: 382233100

Add SSL_CREDENTIAL native methods.

---

common/src/jni/main/cpp/conscrypt/jniutil.cc
common/src/jni/main/cpp/conscrypt/native_crypto.cc
common/src/main/java/org/conscrypt/NativeCrypto.java
common/src/main/java/org/conscrypt/NativeRef.java

Adds calls to register spake and add credentials to the ssl_ctx. 
Change-Id: I39bbf81ef831c66af81239b6a715532da55d2765
Test: SpakeTest
Bug: 382233100

Add Spake Credential registration native code.

---

android/src/main/java/org/conscrypt/Platform.java
common/src/main/java/org/conscrypt/metrics/ReflexiveStatsEvent.java
openjdk/src/main/java/org/conscrypt/Platform.java
platform/src/main/java/org/conscrypt/Platform.java
platform/src/test/java/org/conscrypt/metrics/MetricsTest.java

Refactor ReflexiveStatsEvent.getSdkVersion into Platform.getTargetSdkVersion
Resubmit with checking for NoSuchMethodException
Change-Id: Iffaa69a82056127202325f7513cc9d53ce4890cb

Refactor ReflexiveStatsEvent.getSdkVersion into Platform.getTargetSdkVersion

---

common/src/test/java/org/conscrypt/NativeCryptoArgTest.java

Change-Id: I36a2fe7e7e1fdf023d3667edd797294079b78e10
Test: atest NativeCryptoArgTest

Move Spake NativeArgs testing to NativeCryptoArgTest

---

common/src/main/java/org/conscrypt/KeySpecUtil.java
common/src/main/java/org/conscrypt/OpenSSLXDHKeyFactory.java
common/src/main/java/org/conscrypt/OpenSslEdDsaKeyFactory.java
common/src/main/java/org/conscrypt/OpenSslSlhDsaKeyFactory.java
common/src/test/java/org/conscrypt/KeySpecUtilTest.java
openjdk/src/test/java/org/conscrypt/ConscryptOpenJdkSuite.java

makeRawKeySpec is now duplicated in three different places. It is better to move them into a single place.

Move makeRawKeySpec into a small library.

---

common/src/main/java/org/conscrypt/metrics/ConscryptStatsLog.java
common/src/main/java/org/conscrypt/metrics/GeneratedStatsLog.java
common/src/main/java/org/conscrypt/metrics/StatsLogImpl.java

This is needed to log metrics to statsd.
Test: atest MetricsTest
Bug: 404740863
Merged-In: I524f07a864c88272fc5b4044644679836abca82b
Change-Id: I524f07a864c88272fc5b4044644679836abca82b

Add statslog java library to conscrypt

---

common/src/main/java/org/conscrypt/NativeSsl.java
common/src/main/java/org/conscrypt/SSLParametersImpl.java
platform/src/test/java/org/conscrypt/SpakeTest.java

Test: atest SpakeTest
Change-Id: I50cda49217af4aaf6b78ac954ae00090193a044d

Add better checks for tls1.3 inclusion for spake

---

common/src/main/java/org/conscrypt/OpenSSLAeadCipher.java
common/src/main/java/org/conscrypt/OpenSSLAeadCipherAES.java
common/src/main/java/org/conscrypt/OpenSSLAeadCipherChaCha20.java
common/src/main/java/org/conscrypt/OpenSSLCipher.java
common/src/main/java/org/conscrypt/OpenSSLCipherChaCha20.java
common/src/main/java/org/conscrypt/OpenSSLCipherRSA.java
common/src/main/java/org/conscrypt/OpenSSLEvpCipher.java
common/src/main/java/org/conscrypt/OpenSSLEvpCipherAES.java
common/src/main/java/org/conscrypt/OpenSSLEvpCipherARC4.java
common/src/main/java/org/conscrypt/OpenSSLEvpCipherDESEDE.java
common/src/main/java/org/conscrypt/metrics/MetricsAlgorithm.java
common/src/main/java/org/conscrypt/metrics/MetricsCipher.java
common/src/main/java/org/conscrypt/metrics/MetricsMode.java
common/src/main/java/org/conscrypt/metrics/MetricsPadding.java
common/src/main/java/org/conscrypt/metrics/NoopStatsLog.java
common/src/main/java/org/conscrypt/metrics/StatsLogImpl.java

Pending actual atom creation.
Bug: 404740863
Test: atest MetricsTest
Merged-In: Ie0f8454fb9b04774584fbe95e9af6d77db501e8e
Change-Id: Ie0f8454fb9b04774584fbe95e9af6d77db501e8e

Add cipher usage metrics to Conscrypt

---

common/src/test/java/org/conscrypt/java/security/SignatureTest.java
testing/src/main/java/org/conscrypt/TestUtils.java

So we can use it with other algorithms such as Mac.

Factor stress test code out into TestUtils.

---

common/src/jni/main/cpp/conscrypt/native_crypto.cc

Fix mldsa public key size buffer length.

---

common/src/main/java/org/conscrypt/OpenSSLX509CertificateFactory.java

Test: atest X509CertificateTest
Bug: 34952450
Change-Id: Ic646301c57137d9340d2818e5f50241a7b08e273

Allow comments to be added onto PEM certificate files.

---

common/src/jni/main/cpp/conscrypt/native_crypto.cc
common/src/main/java/org/conscrypt/NativeCrypto.java
openjdk/src/test/java/org/conscrypt/NativeCryptoTest.java

To support XWING with HPKE, we only need to be able to create raw key pairs, and enable XWING. Everything else then works.

Add XWING_public_key_from_seed to NativeCrypto.
